fix random_walks references, bump Sphinx floor to 8.2 (#199)
Fixes #198 

## Fixes random walks references

Looks like the removals and reorganization in
https://github.com/rapidsai/cugraph/pull/5122 broke some links here, but
I think we didn't find out about it until now because `sphinx` or `myst`
or something was being overly-permissive.

```text
WARNING: [autosummary] failed to import cugraph.node2vec_random_walks.node2vec_random_walks.
Possible hints:
* ModuleNotFoundError: No module named 'cugraph.node2vec_random_walks'
* AttributeError: 'function' object has no attribute 'node2vec_random_walks'
* ImportError: 
WARNING: [autosummary] failed to import cugraph.random_walks.
Possible hints:
* ImportError: 
* AttributeError: module 'cugraph' has no attribute 'random_walks'
* ModuleNotFoundError: No module named 'cugraph.random_walks'
```

Those broken links now result in hard build failures (yay!). This fixes
them.

## Fixes `cugraph-pyg` references

Builds were failing with what turned out to be an import error:

```text
      File "/opt/conda/envs/docs/lib/python3.14/site-packages/sphinx/events.py", line 415, in emit
        raise ExtensionError(
        ...<4 lines>...
        ) from exc
    sphinx.errors.ExtensionError: Handler <function process_generate_options at 0x73f1825db8a0> for event 'builder-inited' threw an exception (exception: no module named cugraph_pyg.data.feature_store)
```

Fixed by https://github.com/rapidsai/cugraph-gnn/pull/470 and related
PRs in https://github.com/rapidsai/build-planning/issues/284

## Resolves Sphinx warning

> WARNING: The config value `linkcode_resolve' has type `partial';
expected `NoneType' or `function'.

Looks like this is new validation that was added in `Sphinx` 8.2
(https://github.com/sphinx-doc/sphinx/pull/13324), so this PR also bumps
the `sphinx` floor to 8.2.